package(
    default_visibility = ["//src:__subpackages__"],
)

android_library(
    name = "main",
    srcs = [
        "java/nl/tcilegnar/weer9292/**/*.kt",
    ],
    manifest = "AndroidManifest.xml",
    resource_files = glob(["res/**"]),
)